[tool.poetry]
name = "sport-activities-features"
version = "0.1.0"
description = ""
authors = ["iztokf <iztokf@iztok-jr-fister.eu>"]

[tool.poetry.dependencies]
python = "^3.9"
python-tcxparser = "^1.1.0"
matplotlib = "^3.3.3"
geopy = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
